# Generated by Django 2.2 on 2019-05-11 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0002_auto_20190510_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='tipo',
            field=models.CharField(choices=[('DBT', 'Débito'), ('CRD', 'Crédito'), ('TRF', 'Transferência')], default='DBT', max_length=3),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='journal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lancamentos.Journal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lancamento',
            name='tipo',
            field=models.CharField(choices=[('DBT', 'Débito'), ('CRD', 'Crédito'), ('TRF', 'Transferência')], default='DBT', max_length=3),
        ),
    ]
