# Generated by Django 2.2 on 2019-05-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0003_auto_20190511_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='periodicidade',
            field=models.CharField(choices=[('UNI', 'Único'), ('SEM', 'Semanal'), ('MES', 'Mensal'), ('ANO', 'Anual')], default='UNI', max_length=3),
        ),
        migrations.AddField(
            model_name='journal',
            name='qtde_parcelas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='tempo_indeterminado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='ultima_atualizacao',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lancamento',
            name='num_parcela',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
