# Generated by Django 2.2 on 2019-05-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0004_auto_20190511_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamento',
            name='tipo',
        ),
    ]
