# Generated by Django 2.2.1 on 2019-05-12 21:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lancamentos', '0006_auto_20190512_1843'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conta',
            unique_together={('nome', 'proprietario')},
        ),
    ]
