# Generated by Django 2.2 on 2019-06-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0007_auto_20190512_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='parcela_inicial',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
