# Generated by Django 2.2 on 2019-06-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0008_journal_parcela_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
