# Generated by Django 2.2 on 2019-06-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0010_auto_20190621_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='parcela_inicial',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='qtde_parcelas',
            field=models.IntegerField(null=True),
        ),
    ]
