# Generated by Django 3.0.1 on 2019-12-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0013_auto_20190621_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='descricao',
            field=models.TextField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lancamento',
            name='descricao',
            field=models.TextField(default='Migrado', max_length=250),
            preserve_default=False,
        ),
    ]
